create table client (id bigint generated by default as identity (start with 1), name varchar(255), primary key (id));
insert into client(id, name) values (default, 'Johnas Doe');
insert into client(id, name) values (default, 'Jane Doe');
insert into client(id, name) values (default, 'Jonnie Doe');